if (process.env.NODE_ENV === 'development') {
	window.env = {
		api: {
			airdropUrl: 'http://www.holatoken.xyz//api/v2/airdrop',
			// airdropUrl: 'http://localhost:5000/api',
			applogicUrl: 'http://localhost:9002/api/v2/applogic',
			authUrl: 'http://localhost:9002/api/v2/barong',
			finexUrl: 'http://localhost:9002/api/v2/finex',
			ieoAPIUrl: 'http://www.holatoken.xyz//api/v2/ieo',
			rangerUrl: 'ws://localhost:9003/api/v2/ranger',
			referralUrl: 'http://www.holatoken.xyz//api/v2/referral',
			stakeUrl: 'http://www.holatoken.xyz//api/v2/stake',
			sunshineUrl: 'http://www.holatoken.xyz//api/v2/sunshine',
			tradeUrl: 'http://localhost:9002/api/v2/peatio',
			walletUrl: 'http://localhost:4000/api',
			transactionUrl: 'http://localhost:4000/api',
			statisticUrl: 'http://localhost:4000/api',
			competitionUrl: 'http://localhost:4000/api',
			newKycUrl: 'http://localhost:4000/api',
			bannerUrl: 'http://localhost:4000/api',
			withdrawLimitUrl: 'http://localhost:4000/api',
		},
		minutesUntilAutoLogout: '5',
		withCredentials: false,
		gaTrackerKey: '',
		rangerReconnectPeriod: '1',
		msAlertDisplayTime: '5000',
		incrementalOrderBook: true,
		finex: true,
		isResizable: false,
		isDraggable: false,
		languages: ['en', 'ru'],
		sessionCheckInterval: '15000',
		balancesFetchInterval: '3000',
		passwordEntropyStep: 14,
		showLanding: true,
		sentryEnabled: false,
		kycSteps: ['email', 'phone', 'profile', 'document', 'address'],
	};
}
